spring:
  profiles:

  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:mbtidb
#    username: sa
#    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(/EuZtzFTcrvpL4YaEMN4qiF18s3ht8/aX8fMRHikzre2DxGVTAhMI6AGYuUL2Q17WAFdWVDeivIoMC1/nPsYnTKJx97c8L1ZSNWZ26JckZn/zAjPw7VrHXYMm+ofCAx/IWd2ZVN03pU=)
    username: ENC(AxC0v+DOPG8HW0hwaP93UA==)
    password: ENC(QGWtjq/KUQGj4FUeAu06wYT1QISnhAXh)

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

  redis:
    host: localhost
    password:
    port: 6379

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

cloud:
  aws:
    credentials:
      accessKey: ENC(/5EGL3hSUR/WlHl596vqssRjCUYXAwAqDHYxXiOpJxc=)
      secretKey: ENC(1+yW5uZkg2LR9Qci32fAjQnnS5UjAdy0H/LeiJo7H6PBqmNHxr/vl1+nkEG3M8etMGd3wn/g4bA=)
    s3:
      bucket: bizchemy-bucket-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 8080

sentry:
  dsn: https://ce63463040a74b5e9c88b5499c256cf8@o1119561.ingest.sentry.io/6154130
  logging:
    enabled: true
    minimum-event-level: info
    minimum-breadcrumb-level: info
  debug: true
  sample-rate: 1
  traces-sample-rate: 1

---

spring:
  profiles: set1

server:
  port: 8081

---

spring:
  profiles: set2

server:
  port: 8082